# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=1, max_length=20, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default=1, max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
