# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=1, max_length=200, verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(default=1, max_length=200, verbose_name='个人网站、博客'),
            preserve_default=False,
        ),
    ]
