# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
