# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20170930_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
